### ISSUE TITLE
Error while running on server

### ISSUE THREAD

**Issue by ryouchaa** [faridzy/fuzzy-sugeno#1]
Warning: require(C:\xampp\htdocs\ai-gastro/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ai-gastro\index.php on line 24

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\ai-gastro/vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\ai-gastro\index.php on line 24

**Comment by faridzy** [comment]
Dont use php artisan serve for running this application, please running  with localhost/foldernameyouraplication
